#pragma once

typedef enum errorCodes{
    NOT_ENOUGH_ARGUEMENTS,
    TOO_MANY_ARGUEMENTS,
    INVALID_ARGUEMENT,
    UNKNOWN_FLAG,
    NOT_A_FLAG,
    INVALID_EPSILON,
    TOO_SMALL_EPSILON,
    TOO_BIG_EPSILON,
    INVALID_INT,
    INVALID_DOUBLE,
    UNABLE_TO_OPEN_FILE,
    NORMAL
} errorCodes;